apiVersion: v1
kind: Service
metadata:
  name: hello-gateway-service
spec:
  type: NodePort
  selector:
    app: hello-gateway
  ports:
    - name: proxy
      port: 3000
      protocol: TCP
      targetPort: 10000
    - name: admin
      port: 3001
      protocol: TCP
      targetPort: 10001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-gateway
  template:
    metadata:
      labels:
        app: hello-gateway
    spec:
      volumes:
        - name: envoy
          configMap:
            name: envoy-config
      containers:
        - name: hello-gateway
          image: hello-py:v3
          command: ["gateway"]
          ports:
            - containerPort: 8000
        - name: envoy
          image: envoyproxy/envoy:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: envoy
              mountPath: /etc/envoy/
          command:
            - "/usr/local/bin/envoy"
          args:
            - "--config-path /etc/envoy/envoy-hello-gateway.yaml"
          ports:
            - containerPort: 10000
              name: envoy-sidecar
            - containerPort: 10001
              name: envoy-admin
            - containerPort: 50051
              name: envoy-grpc
